### ISSUE TITLE
最新的lua 如何再在C里面得到JNIEnv *env指针？

### ISSUE THREAD

**Issue by androlua** [nwdxlgzs/xuanlv_Manager#1]
最新的lua 如何再在C里面得到JNIEnv *env指针？

**Comment by nwdxlgzs** [comment]
> 最新的lua 如何再在C里面得到JNIEnv *env指针？

?你是谁?，指针你可以魔改SO时留下接口就行

**Comment by androlua** [comment]
nirenr以前的4.4.2版本没有问题！  最新版按照luajava里面的方法JNIEnv *checkEnv(lua_State *L);   按照这个方法获取直接崩了；同样JNIEnv *getEnvFromState(lua_State * L); 也是不行........
